activeRepository: test
registry:
  - repository:
      url: http://192.168.1.88:8080/snapshots
      username: admin
      password: secret 
    name: test
  - repository:
      url:
      username: invalid
      password: 12345
    name: test_2
